<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('tutorial', function(){
    return view('tutorial');
});

Route::get('/', 'IndexController@Index')->name('index');

//Route::get('proba', function(){
//    $users = [
//        ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
//        ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2' ],
//        ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
//        ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
//        ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
//        ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
//        ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7']
//    ];
//    return view('proba')->with('users', $users);
//});


Route::get('proba', 'ProbaController');

Route::get('proba_get', function(){
    return [

        'items' => [
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2'],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['1.', 'login_1', 'login_1@example.com', 'Famaly_1', 'Otchestvo_1', 'Name_1'],
            ['2.', 'login_2', 'login_2@example.com', 'Famaly_2', 'Otchestvo_2', 'Name_2' ],
            ['3.', 'login_3', 'login_3@example.com', 'Famaly_3', 'Otchestvo_3', 'Name_3'],
            ['4.', 'login_4', 'login_4@example.com', 'Famaly_4', 'Otchestvo_4', 'Name_4'],
            ['5.', 'login_5', 'login_5@example.com', 'Famaly_5', 'Otchestvo_5', 'Name_5'],
            ['6.', 'login_6', 'login_6@example.com', 'Famaly_6', 'Otchestvo_6', 'Name_6'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
            ['7.', 'login_7', 'login_7@example.com', 'Famaly_7', 'Otchestvo_7', 'Name_7'],
        ],
       'heads' => [
           ['Id', 'Логин', 'Почта', 'Фамилия', 'Отчество', 'Имя']
        ]
    ];
});

//Route::get('admin', function(){
//    return view('ringer/admin-panel::index');
//});

//Route::get('/admin/{any}', function($any){
//
//    dd($any);
//
//    return view('ringer/admin-panel::index');
//})->where('any', '.*');
